[project]
name = "morpho-corpus"
version = "0.1.0"
description = "Azerbaijani morphological analysis toolkit"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "gradio>=5.29.1",
    "openpyxl>=3.1.5",
    "pandas>=2.2.3",
    "scikit-learn>=1.6.1",
]
